const SET_PRODUCTS = "SET_PRODUCTS";
const SELECTED_PRODUCT = "SELECTED_PRODUCTS";
const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCTS";

export { REMOVE_SELECTED_PRODUCT, SELECTED_PRODUCT, SET_PRODUCTS };
